# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNFFmpeg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SNFileManager'

  target 'SNFFmpegTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SNFFmpegUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
