# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 inhibit_all_warnings!

target 'SNFFmpeg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'SNFileManager'
  pod 'mobile-ffmpeg-min'

  target 'SNFFmpegTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SNFFmpegUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
